### PR TITLE
COREXY : correction on the display function system_convert_axis_steps_to_mpos

### PR DESCRIPTION
**Pull request by phd0**
on COREXY mode, a move on X axis only display the good position on display with the <code>?</code> command. 
But a simple move on Y axis don't display the good number on Y axis. And change the value of Z axis too ...
This work fine. tested on X,Y and Z direction.

### CODE REVIEW

**Comment by chamnit** [comment]
Thanks for the bug fix. I'll add this manually to the edge branch in my next push later today.

**Comment by phd0** [comment]
there is some Pb with my code : please use 
<code>[B_MOTOR] - steps[A_MOTOR]</code> to correct the sign of the Y axis

**Comment by chamnit** [comment]
The equation is correct, according to CoreXY formulas. Please make sure your motors are spinning in the correct directions as the corexy diagrams show.

**Comment by phd0** [comment]
well, without this correction,  when a put a <code>G0X0Y40</code>
i have a <code>< Idle,MPos:0.000,-40.000,0.000,WPos:0.000,-40.000,0.000 ></code> but the real move seems correct (motor_A and motor_B rotates in the opposite direction)

**Comment by chamnit** [comment]
@phd0 : Have you invert any of the stepper directions in Grbl's settings?

**Comment by phd0** [comment]
no : <i>DEFAULTS_GENERIC</i> config ; only change number of **$100..$132** parameters

**Comment by chamnit** [comment]
Ok. I think there is a problem elsewhere. Can you try replacing planner.c lines 280-281 with:

```
    block->steps[A_MOTOR] = labs((target_steps[X_AXIS]-pl.position[X_AXIS]) + (target_steps[Y_AXIS]-pl.position[Y_AXIS]));
    block->steps[B_MOTOR] = labs((target_steps[X_AXIS]-pl.position[X_AXIS]) - (target_steps[Y_AXIS]-pl.position[Y_AXIS]));
```

and planner.c lines 295-297 with :

```
        delta_mm = ((target_steps[X_AXIS]-pl.position[X_AXIS]) + (target_steps[Y_AXIS]-pl.position[Y_AXIS]))/settings.steps_per_mm[idx];
      } else if (idx == B_MOTOR) {
        delta_mm = ((target_steps[X_AXIS]-pl.position[X_AXIS]) - (target_steps[Y_AXIS]-pl.position[Y_AXIS]))/settings.steps_per_mm[idx];
```

**Comment by phd0** [comment]
yess !
work correctly with the good motor turn in Y move, and Y axis is positive in G0Y40 command

**Comment by chamnit** [comment]
Great! Thanks for checking. Let me know if you have any other CoreXY problems. I don't have a machine to test it on and haven't heard back from any other CoreXY users on how it works.

**Comment by phd0** [comment]
so my first test is made with ... a machine that has not moved beyond plan, but it's going to

**Comment by phd0** [comment]
some change in **planner.c** lines 420-436 too ; It seems got the same bug like **system.c**
<pre>
void plan_sync_position()
{
  // TODO: For motor configurations not in the same coordinate frame as the machine position,
  // this function needs to be updated to accomodate the difference. 
  uint8_t idx;
  for (idx=0; idx<N_AXIS; idx++) {
    pl.position[idx] = sys.position[idx];
    #ifdef COREXY
     if (idx==A_MOTOR) { 
        pl.position[idx] = (sys.position[A_MOTOR] + sys.position[B_MOTOR])/2;
     } 
	 if (idx==B_MOTOR) { 
        pl.position[idx] = (sys.position[A_MOTOR] - sys.position[B_MOTOR])/2;
     }
    #endif
  }
}
</pre>

**Pull request closed without merging**
