### PR TITLE
add all the relevant parts from my laser branch to edge

### PR DESCRIPTION
**Pull request by alpharesearch**
Here is my first proposal for the laser mode that allows to use the variable spindle feature to set the S value at real time.

### CODE REVIEW

**Comment by mkeyno** [comment]
@alpharesearch  do you know any official laser mode for GBRL or probably some links to successful practice?

**Comment by chamnit** [comment]
@mkeyno : Grbl v1.1 was just released and has a laser mode.

**Comment by mayhem2408** [comment]
And it is awesome. I am getting fantastic results. Stutter free movement at 2000-3000 feed rates. No dark edges (thanks to M4 mode). I am moving all my hardware over to GRBL V1.1 from Marlin.
20161213_115942s
20161213_120141s
20161213_120250s

**Comment by tklus** [comment]
Looks great John!
What are you using for generating gcode for the images.

I have tried a few programs but haven't had much luck getting nice shades of gray. Can you point me to some setup tips?

Thanks!
Tim

Sent from my iPhone

On Dec 12, 2016, at 5:13 PM, John <notifications@github.com<mailto:notifications@github.com>> wrote:


And it is awesome. I am getting fantastic results. Stutter free movement at 2000-3000 feed rates. No dark edges (thanks to M4 mode). I am moving all my hardware over to GRBL V1.1 from Marlin.
[20161213_115942s]<https://cloud.githubusercontent.com/assets/4693903/21123532/64b2fc42-c12d-11e6-99c3-fcb2a3462ffe.jpg>
[20161213_120141s]<https://cloud.githubusercontent.com/assets/4693903/21123529/6493174c-c12d-11e6-9d1d-53e905669788.jpg>
[20161213_120250s]<https://cloud.githubusercontent.com/assets/4693903/21123530/649be106-c12d-11e6-9274-df733f94a909.jpg>

-

**Comment by alpharesearch** [comment]
@mkeyno the new 1.1 version is far superior than anything we had the last 2 years. As others said check out the M4 mode.
@tklus on the development threat people talked about laserweb3, I tried it and it is good. But I dont know what @mayhem2408 is using.

**Comment by mayhem2408** [comment]
I have used LaserWeb3 and simply used a text editor to change M3 to M4. The results speak for themselves.

**Comment by mayhem2408** [comment]
I have also photoshoped the photos before feeding them into Laserweb3 as I have found my lasers shading is not linear. 60% and up looks pretty much the same and 15% and below does nothing. Half way at 38% is not too dark on my setup, so I adjust the gamma curve which looks bad on screen, but great on the laser. I am currently working on an Inkscape extension that will do all the work and generate the g-code. I'll post more about that as it evolves.

**Comment by tklus** [comment]
That sounds great! I currently use Inkscape and laser etch from jtech for black and white engraving.

Look forward to the plug in!

Thanks
Tim

Sent from my iPhone

On Dec 12, 2016, at 7:15 PM, John <notifications@github.com<mailto:notifications@github.com>> wrote:


I have also photoshoped the photos before feeding them into Laserweb3 as I have found my lasers shading is not linear. 60% and up looks pretty much the same and 15% and below does nothing. Half way at 38% is not too dark on my setup, so I adjust the gamma curve which looks bad on screen, but great on the laser. I am currently working on an Inkscape extension that will do all the work and generate the g-code. I'll post more about that as it evolves.

-

**Comment by villamany** [comment]
Hi guys,  great news.  I need some spare time for testing the new GRBL.  At the moment i use a old alpharesearch version due i get better performance (more engraving speed without micropicauses) than the latest alpharesearch one. 

... For those playing with image to gcode applications,  you can test the 3dpBurner Image2gcode and sender applications from here http://3dpburner.blogspot.com/p/files.html

**Comment by villamany** [comment]
Hi again, tested the new GRBL 1.1 in laser mode, but i still getting the best performance (higher engraving speeds without micro-pauses) by using the GRBL Alphareseach mod dated as version available at 4 Feb 2015 (https://drive.google.com/file/d/0B5Y1gEmSHMjMS1R4RUhsamV3QXc/view?usp=sharing)

Using a 3dpBurner type laser engraver and depending of engraved resolution i can reach these speeds without micro-pauses=constant speed and more smooth engravings:
resol(mm)    speed(mm/min)
0.08              2800
0.07              2600
0.06              2300
0.05              1700
0.04              1500

With the GRBL 1.1 in same configuration i can't reach that speeds.
This can be also noticed by the working time. Engraving the same 40x35mm picture: 9min37sec when using the Alpharesearch and 10min59sec for GRBL1.1

**Comment by chamnit** [comment]
@villamany : Others have not reported this large of a speed difference. It should be nearly identical. Likely the main difference is how M3, M4 and M5 commands are handled. I enforce a stop anytime these change. You can avoid stopping and turning off the laser by programming a zero spindle speed `S0`. This is valid g-code for turning off the spindle without altering its modal state. 

Also make sure you use the new 'M4' dynamic mode. It only pauses for M3, M4, M5 changes.

**Comment by chamnit** [comment]
@villamany : There is also the consideration that v1.1 had to free up a little more RAM by reducing the planner buffer by a block or two for the new realtime overrides in v1.1.  Feed override alters rate, but doesn't alter dynamically scaled power, while spindle override alters the dynamically scaled power. This allows you to quickly dial in a laser job. 

The smaller planner buffer can reduce the max speed because the planner has to plan within the motions it has in it. In other words, the short line segments of a raster job can limit the amount of distance inside the planner. And limit the top speed. 

I'll be updating the Mega2560 branch soon to v1.1 as well. You'll have at least double the planner buffer there and will likely perform significantly better than either versions.

**Comment by villamany** [comment]
On the past, i tested newer Alpharesearch versions but always go back to the dated as 4 Feb 2015 due to better performance.

I never use M5 for powering off the laser when raster engravigs, i use M3S0 instead so no problem from here.

Im now testing M4 mode for the GRBL1.1 for the same file instead use M3 but this is really slower (estimated remaining time is about 1hour instead some minutes).

My configuration for 1.1 is this, maybe you can see any cause here (note Z axis is not used):
$0=10
$1=255
$2=0
$3=0
$4=0
$5=0
$6=0
$10=6
$11=0.020
$12=0.010
$13=0
$20=0
$21=0
$22=1
$23=1
$24=200.000
$25=4000.000
$26=0
$27=0.000
$30=255
$31=0
$32=0
$100=80.000
$101=80.000
$102=0.001
$110=12000.000
$111=12000.000
$112=12000.000
$120=1200.000
$121=1200.000
$122=12000.000
$130=355.000
$131=520.000
$132=10000.000

The file used for testing is simple, you can open with Notepad and mod the F Speed and M3/M4 modes at  begining of the file. It is 40x35mm diagonal raster engraving with the laser scaled from 0-255 power values: https://drive.google.com/file/d/0B5Y1gEmSHMjMckRJS1hqU3A1SDA/view?usp=sharing

**Comment by chamnit** [comment]
@villamany : Did you enable laser mode ($32=1)? Your settings show it's still disabled.

**Comment by villamany** [comment]
Opss. Sorry, i forgot it with many files opened on my computer.
However, now tested with $32=1 and M4 and the same result, unsmooth motor sounds an higher total time of:
11min 13seg for v1.1 M4 mode
10min 59sec for v1.1 M3 mode
9min 37sec for Alphareserach

**Comment by chamnit** [comment]
@villamany : Not sure why you are getting non smooth motion. You shouldn't. How are you streaming your gcode?

**Comment by villamany** [comment]
By using the character count system, with 3dpBurner Sender app https://github.com/villamany/3dpBurner-sender/releases/download/v1.1/3dpBurnerSender.exe

**Comment by villamany** [comment]
Buffer block report to stay about 17 on the Alpharesearch while the full job, if i am correct it should be equivalent to about 0 on the newer v1.1 buffer free report, however stays above 0 always

**Comment by chamnit** [comment]
@villamany : Fair enough. I downloaded your file and it looks like you are well exceeding the capabilities of the Arduino. You are sending a g-code line on average every 2.7 ms. This is crazy fast. At this rate, I'm not surprised that v1.1 is a little slower. It has a quite a bit more to do to enable overrides, than v0.9. (If you haven't used overrides, please do. They change how you can use a machine.)

In the worst case scenario, I've timed v0.9 to be need about 4 ms per g-code line. It'll often go a bit faster. Likely down to your 2.7ms per line. I haven't timed what the minimum g-code rate for v1.1 is yet, but based on your testing it's about 3.3ms per line. I think that's perfectly acceptable. Any better will have to wait until the Grbl ARM version coming out soon. :)

I suppose the question now should be, is there any difference in quality? Particularly with M4 dynamic power mode? It should be significantly cleaner and have a lot less burning.

**Comment by chamnit** [comment]
Also, at these high rates, I think you are seeing the effects of the slightly smaller planner buffer. It has plan one or two more blocks per g-code line than a larger one. I won't explain why, but it does in certain scenarios like this one. For the most part, I don't think this is a problem with Grbl, but instead hitting the limits of what an Arduino can do.

**Comment by villamany** [comment]
Great, waiting the ARM version. Yes i know im on the limit of Arduino power, i search that limit for each resolution i use for engravings, also tested lowering the steps/mm and stepper resolution for lower Arduino load but no much difference.
The laser needs more speed for getting all his power up. At this 3000mm/min speed i need to cut the max power to about PWM180 instead the max PWM255, so any speed improvement will speed up the things. My laser is 2-3W but now there are much more powerfull laser diodes on the market, so more speed is very welcome.

Overrride is a great tool for getting the best settings like the other great features on th v1.1, but if preffer speed over that so probably still on my actual version. 
For the moment no much issues with accelerations on vectorial engravings or cuttings, only on raster engravings with a square mark arround picturem but this has an easy solution by adding a white frame to the image, by this way all accelerations are made on the white frame without burning, so no marks.

Many thanks for your great work chamnit, i really apreciate it. Probably one of the best projectscfor the maker world

**Comment by chamnit** [comment]
@villamany : One of the main issues is not the controller, but the g-code that controls lasers. There isn't a command that take care of a raster process well. They are very short straight lines, usually evenly spaced, with only a spindle speed alteration. No matter the controller, even ARM, you will always hit a limit of how quickly you can stream these G1 Sx line segments. I really think there needs to be a special g-code for rastering to insert multiple Sx values over a longer line segment. But that is a topic that should be discussed on the proper thread.

With M4 dynamic mode, you don't need the extra white space around your image. You should be able to remove it and a get shorter process time. Not sure how much shorter but it might be faster than prior test if you try this.

**Comment by mayhem2408** [comment]
I am feeding at a rate of F4000. My Rasters at 0.1mm resolution, so I'm burning just under 700 pixels per second. I am also generating gcode to 100 shades of gray, so the code it quite large. I've optimized my g-code to make it as small as possible, like
G1X14.5S545
I'm having no problems keeping the buffers full.

I've even tested F6000, but while my laser isn't powerful enough to produce a nice burn at that speed, GRBL was able to keep up.

That being said, I have been using a modified version of Marlin for lasers for a while which has a raster gcode called G7 which you can set the resolution, direction and feed it base64 encoded strings to raster. It produces much less serial data and much smaller files. Example, on 50 pixels of G1 gode will consume about 600 bytes. The same thing using Marlins G7 will only take about 70 bytes. Marlin is much slower than GRBL and is the main reason why the G7 mode was created. 

One thought I had and was going to experiment with, but haven't has the time to even start thinking about the code was to allow G1 to have multiple S parameters on 1 line. Example
G1 X10 S123 S234 S524 S126 S765
The idea was to have GRBL work out how long the line is, and break it up into smaller segments based on the number of S parameters sent.
For example,
G0 X0 Y0
F1500
G1 X10 S123 S234 S524 S126 S765
would create the following in the planner
G0 X0 Y0
F1500
G1 X2.0 S123 
G1 X4.0 S234
G1 X6.0 S524
G1 X8.0 S126
G1 X10.0 S765

The would take the serial data required for 5 pixels from 60 bytes down to 26.
Just an idea.......

**Comment by chamnit** [comment]
@mayhem2408 : Ok you win. 1.7ms per line segment is amazing. Thanks for sharing. 

I did a quick search for G7 on Marlin. It looks like the LW3 folks are against messing with g-code unless they have to. I support not messing with g-code too much, but I think there is a good reason to. Not only the file size, I think that as you approach tens of microseconds burn time/pixel, this will become a much much bigger issue. It just doesn't scale.

**Comment by Strooom** [comment]
Interesting discussion.

- One  more idea : on the future ARM version, the interface could be USB RAW-HID (io. Serial), which gives you up to 12 Mbps communications speed.

- On the idea of new G-Code word : I think that during its lifetime, GCode has already evolved quite a lot, adapting itself to the evolution of machine HW. GCode originated before we had 3D printers and laser-cutters. I think it is ok to extend the language with some new words to efficiently feed those new types of machines.

**Comment by alpharesearch** [comment]
@chamnit when you talk about a ARM version what board are your targeting? Something like this:  [Re-ARM](https://www.kickstarter.com/projects/1245051645/re-arm-for-ramps-simple-32-bit-upgrade)?

**Comment by Strooom** [comment]
If taking the step to ARM, I would advise to at least go to a Cortex M4F processor, as it can do 'float' math in hardware.. eg
float multiply : 1 cycle
float divide : 14 cycles
float sqrt : 14 cycles
This way a lot of things can be done in the real-time part, which in turn simplifies design..

The Re-ARM has a Cortex M3 which has no floating point HW.
The few $$ price difference between M4F and M3 are probably irrelevant in the total cost of your machine..

**Comment by alpharesearch** [comment]
@Strooom do you have a board in mind? I guess the Teensy 3.5 and 3.6 would fit the bill.
I guess it would be possible to create some kind of connection board that can take both RAMPs 1.4 and the Teensy 3.5/6 and make the connection.
Or are you suggesting to design something from scratch?

**Comment by chamnit** [comment]
@alpharesearch @Strooom : Let move this discussion [here](https://github.com/gnea/grbl/issues/67). Thanks.

**Pull request closed without merging**
