### PR TITLE
Sleepmode

### PR DESCRIPTION
**Pull request by dguerizec**
This is a quick and dirty sleep mode to release steppers after a few seconds of inactivity.

I read #597 and thought I may give it a try.

### CODE REVIEW

**Comment by chamnit** [comment]
Thanks, but there is already something like this implemented in [Grbl-Mega](http://github.com/gnea/grbl-Mega), which will also park the machine, if necessary. It's not quite what you have here in terms of how it works, but it'll be easy to alter there. I don't plan on adding this to the 328p version of Grbl at this time.

**Comment by dguerizec** [comment]
Thank you for taking the time to handle that incomplete pull-request.

I don't quite understand why it couldn't be implemented on the 328p if it is already on Grbl-Mega (which does not implement 328p if I'm correct).
And I'm wondering what has changed since [that comment](https://github.com/grbl/grbl/issues/597#issuecomment-108922006) ?

I personally don't care much if this feature is released soon or late, as long as I have it on my own CNC. But I feel like it's a bit unfair for all users that have asked for it.

I didn't read all and every issues, so I may have missed something.
Thanks for enlightening me.

**Comment by chamnit** [comment]
@dguerizec : Please keep in mind that Grbl is open-source and free. To say that "it's a bit unfair for all users that have asked for it" is very disturbing to me personally. Because it's open-source, you can alter Grbl however you want and make it your own. There is no requirement for this project to succumb to every user's demands and desires. There are lots of other considerations involved, namely whether or not it makes sense to install a feature when considering its overall usefulness and/or if there are other more critical features that override it. It's arguable that an auto-sleep for steppers is **required** for everyone. It'll be more useful to have an explicit command that turns off the steppers after a job.

If you have not been following the Grbl threads very closely, Grbl v1.0 is set for release very soon, and there are lots of features that are crammed into the last bits of flash and memory the 328p has. The Grbl-Mega repo has no such restriction. When everything has been installed into the 328p Grbl, then we can talk about adding your proposal, but until then please refrain from drawing premature conclusions of being "unfair". Grbl is for everyone, not just a select few users.

**Comment by dguerizec** [comment]
Thanks a lot for your reply. I didn't mean to be rude and if I sounded so, all I have to say is english is not my mother tongue.

Be sure I appreciate the time you spend sorting out every issue and feature. You answered my question and I now understand better why you don't plan to add the sleep mode at this time.

I will patiently wait for the 1.0 release, and probably try the edge branch until then.

**Pull request closed without merging**
