### PR TITLE
Serial Echo Feature

### PR DESCRIPTION
**Pull request by timryder**
Added and tested a Serial Echo feature to echo back each byte of data in the serial input buffer before grbl processes it.  This has helped me already tremendously to discover major flaw in my communication circuit.

### CODE REVIEW

**Comment by chamnit** [comment]
@timryder : I just installed this last weekend. Instead of raw bytes, it return the string that Grbl intends to execute. The string will be pre-parsed (capitalized, spaces removed, no comments).

**Comment by timryder** [comment]
Is that on the edge branch or do you only have it local? I liked personally seeing the raw because i was getting noise at the micro controller which made grbl disregard my string. If we only see the string grbl is intending to use it doesn't help much with debugging? Unless i'm not interpreting your modification correctly?

**Comment by chamnit** [comment]
@timryder : It's on the master branch as a config option near the bottom of the file. I chose the preprocessed version because it's lower overhead and won't tax the system to cause other problems. Although I agree that it's easier to detect differences in raw data, but this is only intended for debugging, not as full time communication protocol thing.

**Comment by timryder** [comment]
Please forgive me and allow me to rebut... if its intended for debugging purposes only, are you truly more concerned about the overhead of the mcu versus the functionality it poses for debug? My final thoughts.  Please feel free to close and reject pull request.

**Comment by chamnit** [comment]
@timryder : It was also chosen to encapsulate the command string into a set `[echo: XXX]` string so GUIs can interpret them correctly and ignore them. If you sent back the exact character when it was sent, it will interfere with the normal communication protocol. GUIs would have no clue what the data coming is.

**Comment by timryder** [comment]
I see.  I was doing testing using just a serial terminal program sending back pre-programmed strings to grbl and watching the responses back. But as you have full GUI's to contend with i can see how that'd be much better implementation.

**Pull request closed without merging**
